- hosts: "{{ hostname }}"
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: False
  vars:
    - packages: ["git", "nmap"]
  tasks: 
    - name: Installing {{ packages }} on {{ hostname }}
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
