# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_user=root
ansible_ssh_user=root
ansible_become=true
ansible_password=Password
openshift_deployment_type=origin
#containerized=true
openshift_router_selector='router=true'
openshift_registry_selector='registry=true'
openshift_master_default_subdomain=10.0.3.28.xip.io
#openshift_check_min_host_memory_gb=6
#openshift_check_min_host_disk_gb
openshift_disable_check=memory_availability,disk_availability
openshift_release="3.9"

openshift_install_examples=false
openshift_docker_insecure_registries=172.30.0.0/16



# enable htpasswd auth
# openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
# openshift_master_htpasswd_users={'admin': '$apr1$zgSjCrLt$1KSuj66CggeWSv.D.BXOA1', 'user': '$apr1$.gw8w9i1$ln9bfTRiD6OwuNTG5LvW50'}

# host group for masters
[masters]
10.0.3.28 openshift_public_hostname=10.0.3.28 openshift_hostname=10.0.3.28

# host group for etcd, should run on a node that is not schedulable
[etcd]
10.0.3.28

# host group for worker nodes, we list master node here so that
# openshift-sdn gets installed. We mark the master node as not
# schedulable.
[nodes]
10.0.3.28    openshift_hostname=10.0.3.28
10.0.3.30 openshift_hostname=10.0.3.30 openshift_node_labels="{'router':'true','registry':'true'}" openshift_schedulable=false
